import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    Playfair_Display,
    Poppins, DM_Sans, Instrument_Serif
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const playfair = Playfair_Display({
    variable: "--font-playfair",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["300", "400", "700"]
});

const inSerif = Instrument_Serif({
    variable: "--font-serif",
    subsets: ["latin"],
    weight: ["400"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn("h-full", dmSans.variable)}>
            <body
                className={`${geistSans.variable} ${inSerif.variable} ${geistMono.variable} ${playfair.variable} ${poppins.variable} antialiased w-full h-full selection:bg-amber-300 selection:text-amber-950`}
            >
                {children}
            </body>
        </html>
    );
}
